### ISSUE TITLE
[NERSC] access to DESC/LSST packages on NERSC via the same stack

### ISSUE THREAD

**Issue by humnaawan** [LSSTDESC/desc-help#10]
**Description**
I'd really like to use CCL, NaMaster, and MAF together on NERSC. As far as I can tell, `desc-python` has CCL and NaMaster, but not MAF. `desc-stack` used to have CCL but it appears to be broken (see #9); it doesn't have NaMaster or MAF.

I am able to use MAF after I source the following though (which is in my `lsst-kernel.sh` file):
`source /global/common/software/lsst/cori-haswell-gcc/stack/setup_current_sims.sh`

I'd really appreciate some help.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [x] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by heather999** [comment]
@humnaawan  I'll address CCL in issue #9 separately, but that should be fixable so it is available in all jupyter kernels.

`NaMaster` is unfortunately not compatible with the version of FFTW distributed with the DMstack (specifically there is a required FFTW OMP library that the stack excludes).  I have inquired with the DM folks: https://lsstc.slack.com/archives/C2K97E3L5/p1564093346029400 and they kindly opened a JIRA to address this in the future: https://jira.lsstcorp.org/browse/DM-20811 but there has not been any action on this yet.  I suspect once they move to support the conda-forge versions of various libraries, such as fftw, this won't be an issue anymore.  For now, `NaMaster` is only available in jupyter kernels without DMstack or lsst_sims - so for now it is just in `desc-python`.

MAF, to my knowledge, is only available in `lsst_sims`, not `lsst_distrib` (aka DMstack). To provide both `lsst_distrib` and `lsst_sims` in the same `desc-stack` release, typically requires I have access to a `lsst_sims` build that is compatible with the release of `lsst_distrib`. The support for `lsst_sims` has dwindled a bit due to Scott Daniel's departure.  We don't have a `lsst_sims` that corresponds to `lsst_distrib` v19 (the version of DMstack used for Run2.2i DRP processing), as such CO decided we could drop `lsst_sims` from `desc-stack` for now, thinking most users do not use the applications only available in sims.  There are a few possibilities:
* We set up another jupyter kernel specifically for `lsst_sims` that includes CCL and MAF.. given the FFTW issue noted above, I don't think I can pull in `NaMaster` but I can double check that.
* We set up a jupyter kernel with everything in `desc-python`, including `NaMaster`, `CCL` plus just what is needed for MAF, which hopefully doesn't include DM's version of FFTW.  Are there other `lsst_sims` utilities that you need?  Having a full list might help determine how feasible this is.

Do you have a sense of how many people rely on `lsst_sims` packages and need them in either a command line python env or via jupyer kernels?

**Comment by heather999** [comment]
Now that we have a new `desc-python` release, this includes both a functional `pyccl` and `NaMaster`
That doesn't take care of MAF yet - but I'll be looking at that next.

**Comment by humnaawan** [comment]
thank you @heather999 ! as for your earlier question re the number of people relying on `lsst_sims`, i'm not exactly sure. if i were to guess, it'd primarily be DESC OSWG but I'd have to inquire re the details.

**Comment by heather999** [comment]
@humnaawan It's been too long, but now with more recent DMstacks moving to conda-forge and some fixes in the sims builds - we have new conda environments available that now provide stack+sims and I can much more easily add in additional packages like `NaMaster`.  These new conda environments/jupyter kernels with DMstack + sims (including MAF) + pyCCL + NaMaster:
```
desc-stack-weekly
desc-stack-weekly-latest
```
These are currently based on DMstack `w_2020_22`.  My intent is that `desc-stack-weekly-latest` will be updated as often as once a week, and then `desc-stack-weekly` will be updated when there is clearly a stable weekly to move to.  Ultimately, one of these will become the new `desc-stack-dev` and then `desc-stack-prod`.

There is also `desc-python-bleed` which is stack-free, but pulls in the latest releases of all packages like CCL, NaMaster, etc

People will have to re-run some set up to gain access to these at NERSC, just once you would do:

`source /global/common/software/lsst/common/miniconda/kernels/setup.sh`
Then you should have these new jupyter kernels available to you in jupyter.nersc.gov

**Comment by heather999** [comment]
@humnaawan It's been too long, but now with more recent DMstacks moving to conda-forge and some fixes in the sims builds - we have new conda environments available that now provide stack+sims and I can much more easily add in additional packages like `NaMaster`.  These new conda environments/jupyter kernels with DMstack + sims (including MAF) + pyCCL + NaMaster:
```
desc-stack-weekly
desc-stack-weekly-latest
```
These are currently based on DMstack `w_2020_22`.  My intent is that `desc-stack-weekly-latest` will be updated as often as once a week, and then `desc-stack-weekly` will be updated when there is clearly a stable weekly to move to.  Ultimately, one of these will become the new `desc-stack-dev` and then `desc-stack-prod`.

There is also `desc-python-bleed` which is stack-free, but pulls in the latest releases of all packages like CCL, NaMaster, etc

People will have to re-run some set up to gain access to these at NERSC, just once you would do:

`source /global/common/software/lsst/common/miniconda/kernels/setup.sh`
Then you should have these new jupyter kernels available to you in jupyter.nersc.gov

**Comment by heather999** [comment]
@humnaawan It's been too long, but now with more recent DMstacks moving to conda-forge and some fixes in the sims builds - we have new conda environments available that now provide stack+sims and I can much more easily add in additional packages like `NaMaster`.  These new conda environments/jupyter kernels with DMstack + sims (including MAF) + pyCCL + NaMaster:
```
desc-stack-weekly
desc-stack-weekly-latest
```
These are currently based on DMstack `w_2020_22`.  My intent is that `desc-stack-weekly-latest` will be updated as often as once a week, and then `desc-stack-weekly` will be updated when there is clearly a stable weekly to move to.  Ultimately, one of these will become the new `desc-stack-dev` and then `desc-stack-prod`.

There is also `desc-python-bleed` which is stack-free, but pulls in the latest releases of all packages like CCL, NaMaster, etc

People will have to re-run some set up to gain access to these at NERSC, just once you would do:

`source /global/common/software/lsst/common/miniconda/kernels/setup.sh`
Then you should have these new jupyter kernels available to you in jupyter.nersc.gov
