### ISSUE TITLE
ROOT for community SN space

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#12]
Would appreciate installing https://root.cern.ch for the SN community space. It is used by the SNANA code.

**Comment by cwwalter** [comment]
Note that ROOT has been built for conda-forge.  For those who don't know, it is the main analysis platform in particle physics.  It's best if you can get a binary release that works.  I would try the conda-forge version first.

**Comment by heather999** [comment]
@RickKessler can you remind me what environment set up you use to build the SNANA code?  I would be inclined to use either NERSC's provided ROOT module or as Chris mentioned the `conda-forge` installation.

**Comment by RickKessler** [comment]
source /global/cfs/cdirs/lsst/groups/SN/snana/SNANA_setup.sourceme

**Comment by heather999** [comment]
@RickKessler Looking over teh SNANA_setup_sourceme reminds me that the env relies on the CVMFS installation of the stack.  Once the DMstack moves to use conda-forge, we'll be in a position to follow Chris' advice and just install root that way. We might be able to utilize NERSC's ROOT v6.18 with py3 support module - I'm a little hesitant because I suspect that is built with gcc7 rather than 8 but it might be ok.  I'd suggest trying it.. and we'll go from there.  So, edit your setup environment to include:  `module load root/6.18.00-py3` and try a build of SNANA and see what happens.  If that fails - we'll have to try something else.

**Comment by RickKessler** [comment]
so far root 6.18 seems to be working. I had to tweak the makeFile to remove libCint for root v6.
