### ISSUE TITLE
[NERSC] Request for LSST-DESC SNANA directory space

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#3]
**Description**
A clear and concise description of what the issue is.  

I would like to request a 1TB shared LSST-DESC environment for SNANA simulation code and outputs (https://github.com/RickKessler/SNANA). The request includes group read and write access for everyone to make life easier. The goal is to run transient (PLASTICC) simulations for a variety of cadences, and to make more refined simulation for SNIa-cosmology studies. I have already installed SNANA in my home dir, and run a short sbatch job.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [X ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by heather999** [comment]
HI @RickKessler,
When you say "The request includes group read and write access for everyone to make life easier." You mean rw access for all DESC NERSC users? That's fine, just want to make sure.  Any preferences for your directory name?  `plasticc`?  `snana`?  My naive thought is to create a subdirectory path like: `groups/SN/plasticc`

When installing SNANA, it looks like there are GSL, cfitsio, potentially ROOT dependencies, etc.  If you haven't already, you may want to take advantage of the [software modules](https://docs.nersc.gov/environment/#nersc-modules-environment) that NERSC provides.  All of the above are generally available, but you may have specific version requirements.  If you run into a situation where you need another version of something like cfitsio, please open an associated issue here in GitHub and we can put in a request to get it installed. By using NERSC's provided libraries you will avoid taking up space (and time!) installing software libraries.  You'll also want to reinstall the software somewhere other than your $HOME directory in any case - generally batch jobs will perform better off $HOME.

For running jobs, you will likely see a performance benefit by using CSCRATCH rather than writing/reading directly from CFS.  Then copy the output data back to CFS when you're done processing. The default CSCRATCH quota is 20 TB per user, so that will hopefully be enough for your jobs and any temporary files.  It is possible to request a temporary increase, and if you guys need that, again just open an issue here, and we can put in a request. As a side note, if you go that route, you will likely want to modify the permissions on the CSCRATCH area you use, to allow read access by users other than the CSCRATCH area owner.  For example, to grant read access to all DESC NERSC users: 

```
setfacl -m g:lsst:x <yourdirectory> (which could be your /global/cscratch1/sd/<username> directory)
mkdir <yourdirectory>/<newdir>
chgrp lsst <yourdirectory>/<newdir>
chmod g+s <newdir>
```

**Comment by RickKessler** [comment]
"rw access for all DESC NERSC users" is correct. The code is safe on Git, and helping each other test and debug is so much easier if everyone can read and write anywhere. I have an INTRO readme file at Chicago which warns of the global rw access, and I can copy this README to NERSC. Lastly, if an urgent code update is needed when I am not available, anyone else can do this without me granting authorization.

Directory: Can we have a top directory called snana (or lsst-desc-snana), and under we can create sub-directories for code and for inputs. I already have an SNANA environment on our U.Chicago cluster (Midway2), and the plan to rsync this environment to NERSC. PLASTICC is the immediate application, but there are other applications for which we may create other folders later under snana. 

 I was able to compile SNANA using the cvfms setup for LSST; it is missing ROOT, but we don't need ROOT for simulations. I may request ROOT later when people get into light curve fitting that outputs tables to ROOT files. The makefile automatically checks for ROOT, and runs according to whether or not ROOT exists.

Writing output to CSCRATCH is great, and we do something similar on our Midway cluster. Can I setup a generic output directory, e.g., $CSCRATCH/SNANA/SIM, so that everyone outputs sim data in one place, yet each person has their own private quota ? Having outputs in one place makes file sharing much easier. If everyone outputs to a separate directory, collaborating is much more difficult.

**Comment by heather999** [comment]
@RickKessler We are working with NERSC to get the 1 TB quota set up in CFS. 

For the CSCRATCH area, we could request a new collaboration account, perhaps named `snaha` (or `desc-snaha`). Such an account would automatically create a $CSCRATCH/desc-snaha directory and we could grant access to some subset of NERSC users.  However, we couldn't set up private quotas - the quota would be shared between the people granted write access to the $CSCRATCH/desc-snaha directory.  We may be able to set up private quotas within the CFS - I just need to see how that process works with NERSC.

**Comment by RickKessler** [comment]
To get things running quicker, how about holding off on the collaboration account and let's start with default user accounts and CSCRATCH the way it is. Based on user experience, we can make modifications later as needed, and we might find issues later that we don't anticipate now. One other thing: it maybe better to label the top level directory 'sn' instead of 'snana'  so that we can install other SN-related code products under the same community space. Other related code products are Pippin, SNCosmo, and some MOF related codes.

**Comment by heather999** [comment]
Whether you want to install all the code on CFS might depend on whether anything is python based or now.. typically we try to install python code in another area at NERSC for performance reasons.  Again, to get things going - you could just go ahead and try to install things under your CFS area and if jobs are not performing well, we will revisit it.
I have the directory space set up in CFS - but I am waiting on NERSC to help set up the quota.  I'm hesitant to just have you start using that until I know for sure that NERSC won't need to recreate the directory.  I will poke them again, and hopefully we will get this off the ground shortly.

**Comment by RickKessler** [comment]
SNANA has very little python, and these are just utilities for MakeFile and plotting. So python performance is not an issue. SNANA is mostly C code, and a little fortran for light curve fitting. Getting started quickly would be useful since people want to generate PLASTICC sims, which just uses C code and doesn't need ROOT.

**Comment by heather999** [comment]
@RickKessler NERSC helped us out and we now know how to get quotas set up properly.  We have a new area with a 1 TB quota, which is RW by any DESC NERSC user.  `/global/cfs/cdirs/lsst/groups/SN/snana`  You can check the status of the quota by doing: `cfsquota snana`
I see you were thinking to change this area to just `sn`, I haven't done that for now.  We will have areas for each of the working groups and some subdirectory structure underneath those. I'd like to stick with `/global/cfs/cdirs/lsst/groups/SN` and then whatever directory name you want under that.  If `snana` is fine, then we're set, otherwise, I can test renaming it.

**Comment by heather999** [comment]
I could also just create a larger SN space which contains a `snana` directory for the whole SN working group.  We're on new ground here to set up this space - we are able to take advantage of this to set things up how we want :)

**Comment by heather999** [comment]
@RickKessler I am going to go ahead and close this issue.  If anything comes up, please feel free to reopen this issue or create a new one.
