### ISSUE TITLE
[NERSC] snana area in the SN group space

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#33]
**Description**
A clear and concise description of what the issue is.  
 should I remove symbolic snana link,
      /global/cfs/cdirs/lsst/groups/SN/snana
  and move the snana directory to  /global/cfs/cdirs/lsst/groups/SN ?

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [X] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by heather999** [comment]
HI @RickKessler We can organize the `/global/cfs/cdirs/lsst/groups/SN` however the SN group prefers.  Right now, the `/global/cfs/cdirs/lsst/groups/SN/snana` area has its own separate quota (1 TB) from the whole SN area (9 TB).  This is primarily due to snana being the first area we had the ability to grant specific quotas and my own inexperience with how NERSC set this up.  Later I added in the SN WG area `/global/cfs/cdirs/lsst/groups/SN`.
We could move the contents of `/cfs/cdirs/lsst/groups/SN/snana` symlink so that it is truly stored in `/cfs/cdirs/lsst/groups/SN` and then I'll just eliminate the 1 TB snana quota and add it to the SN area, and it will have a quota of 10 TB.

It's really up to you and the SN WG, just let me know and I can help fix up the quotas.

**Comment by RickKessler** [comment]
I was mainly worried about the older SNANA disk space being removed at some point for a migration, but if it's stable then we can leave it until there is a more compelling reason to move it.
