### ISSUE TITLE
[NERSC] updating SN miniconda 

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#34]
**Description**
A clear and concise description of what the issue is.  

I would like to install pippin under /global/cfs/cdirs/lsst/groups/SN; there's a miniconda install  under lsst/groups/SN/miniconda3, what is the bashrc addition to activate it on login?

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [X] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by heather999** [comment]
Hi @RickKessler The `/global/cfs/cdirs/lsst/groups/SN/miniconda3` area was installed back in 2018 (python 3.6.1 and conda 4.3.21) and I suspect is outdated.  It could be that the SN WG still uses this and that's fine - but it would be useful to confirm that. Then we should set this up so you guys can more easily keep the conda installation updated with additional packages.

**Comment by RickKessler** [comment]
I think Pippin just needs Python 3, but won't hurt to upgrade to python 3.7. What is the bash command to activate ?

**Comment by heather999** [comment]
I think this miniconda3 install needs to be removed and replaced with a new one.  This installation was originally stored on the old projecta area and was moved during our migration to CFS.  My understanding is that conda installations don't support being moved, as there are some hard-coded paths.. this might even work for now since the projecta area still exists but we really should reinstall miniconda from scratch to avoid unexpected problems.  You could start with a vanilla, more recent miniconda3 - I'm happy to install it if that's useful. If you really want to try it out:

To activate the root environment, given that this is an older miniconda:
```
export PATH=/global/cfs/cdirs/lsst/groups/SN/miniconda3/bin:$PATH
```
To activate the snmachine conda environment (which is also from 2018 and likely should be replaced and/or updated) you can do:
```
conda activate snmachine
```

**Comment by RickKessler** [comment]
Yes, please re-install miniconda3 to avoid potential path conflicts.

**Comment by heather999** [comment]
Hi @RickKessler 
Just installed a more recent Miniconda3 with python 3.7 into: `/global/cfs/cdirs/lsst/groups/SN/software/py3.7`  Right now there is only the root environment, we can add additional conda environments, such as `snmachine`.  To use the top-level root environment and make updates, anyone in the `lsst` UNIX group can do:
`source /global/cfs/cdirs/lsst/groups/SN/software/py3.7/etc/profile.d/conda.sh`

Feel free to create other conda enviroments from this root or let me know if I can help.  
We should also go ahead and remove `/global/cfs/cdirs/lsst/groups/SN/miniconda3` and `/global/cfs/cdirs/lsst/groups/SN/snmachine` since they are outdated and likely unusable.  Should we ask the SN co-conveners about that?  I think ultimately I'd like to confirm with Rahul that it's ok to remove these.

**Comment by RickKessler** [comment]
after doing 
    source /global/cfs/cdirs/lsst/groups/SN/software/py3.7/etc/profile.d/conda.sh
which conda
/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/bin/conda

which seems to still point to an old version ?

**Comment by RickKessler** [comment]
FYI: I started a miniconda3 discussion on slack under desc-sn-pipelines

**Comment by heather999** [comment]
Thanks @RickKessler  I commented on Slack.  While I'm not sure yet what is causing that CVMFS path to be preferred over the CFS install of miniconda in the SN area - I suspect that is in your environment.  Maybe in your $HOME/.basrhc or $HOME/.cshrc or perhaps is something that was set up in your shell before attempting to set up the CFS miniconda.  That particular w_2019_19 CVMFS install is very likely associated with some earlier work for DIAs.

In any case, I think i'll go ahead and do another install in the `/global/common/software/lsst` area - especially if this environment might be used for larger scale batch jobs.  Alternatively, if this conda environment is meant for development - remaining on CFS would be just fine too.  I might just be asking for your use cases and requirements to see if performance is a factor.
Then we'll need to sort out getting this set up appropriately.

**Comment by heather999** [comment]
Hi @RickKessler Comment added to Slack: https://lsstc.slack.com/archives/C94P2DAU8/p1596751370035900
Long story short - I realized i had omitted an important step to activate the conda installation :)  That's why your python wasn't updated when you tried this out the other day.  The missing step was to do `conda activate root` to use the root conda environment.
If you do: `source source /global/cfs/cdirs/lsst/groups/SN/software/setup_sn_python.sh` you will be set up completely to use the new SN miniconda and can add additional conda environments or packages.  I'm happy to help set up conda environment(s) if that's useful to you guys.

**Comment by RickKessler** [comment]
We were able to install Pippin, so I think we are Okay for a while. At some point we may need more assistance when we ramp up a particular classifier that needs gpu's.
