### ISSUE TITLE
[GitHub] Is there a simple way to get admin permissions on a repo?

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/desc-help#35]
I'm opening this issue to capture the interactions in [#desc-co Slack channel](https://lsstc.slack.com/archives/C2M6H2LAX/p1596740447167900) about how to get admin permissions of a LSSTDESC GitHub organization repo. In my case this was linked to register the repo in Zenodo. @jbkalmbach, @dkirkby  and @cwwalter were interested in getting permissions to some repos for similar reasons. 

In my case, @brianv0 kindly modified the permissions of the concrete repo that I neeeded so I was able to start the registration in Zenodo. @dkirkby pointed out that the mechanics of this are a little awkward and, even though there seems to be a chain of trust to assign the admin privileges to different repos, some of the trustees might not be aware that they have such privileges.

@johannct and @heather999 suggested to open this issue in order to capture/document these interactions. Also this might be a good opportunity to evaluate whether we need to re-think about how to proceed for this (it is also the first non-NERSC related issue here!)

**Comment by heather999** [comment]
I think it would be helpful to generate a listing of who has admin privileges on all the repos.  Can you do that @brianv0 ?  Then:
* review that list with the repo developers and WG conveners to make sure the right people are granted admin access on the repos
* document what admins can do and how to do it
* Use the README on each repo to communicate to DESC collaborators who they should contact when they need to complete actions requiring admins.
* Going forward, the admins on the individual repos should manage admin access, including adding/transferring/revoking access when that is appropriate.

**Comment by yymao** [comment]
I wonder if it's better to create an "admin" team for each repo, can grant admin permission to that team instead of to individuals. This way, all DESC github members can see who's on the admin team and also request to join. 

See here for an example: https://github.com/orgs/LSSTDESC/teams/gcr-catalogs-admin

**Comment by rmandelb** [comment]
@yymao - I agree about creating an "admin" team for each repo (and similarly, having a team for developers with write access).  Another example is the public website repo, which has an [admin team](https://github.com/orgs/LSSTDESC/teams/public-website-admins) and a [developer team](https://github.com/orgs/LSSTDESC/teams/public-website-developers) as documented in the repo README.

This question also came to me recently in a different, specific context: somebody transferred their own private repo into the LSSTDESC organization, but by doing so, they lost admin access to it.  Since I'm one of the owners for the LSSTDESC organization overall, I was asked if I could help.  In this case, the decision process for what to do was quite straightforward: that person had authored all the code and it made sense to give them admin access to their own repo.  I then recommended that they set up associated teams with admin and write access for future development.  Of course, the [LSSTDESC organization owners](https://github.com/orgs/LSSTDESC/people?query=role%3Aowner) can solve problems that arise in unusual situations like the one I mentioned, but we should have repo-specific admins for all actively used repositorities.

Going back to @heather999 's question about LSSTDESC repos, there are an awful lot of them.  So to start simpler, I wonder if we could first check for the few most actively used repositories in the LSSTDESC organization what their situation is, just to get a sense of whether this is a common problem?  For example, I just looked at CCL and found that it has multiple admins and a long list of people with write access, but no teams to organize that access.   TXPipe is similar (1 admin, a few with write access, no teams).  So that's a case of two very actively used repos that _do_ have individuals with admin access, and those individuals are generally playing some leading role in the software development (-> it's good that they have admin access).  The fact that they've not chosen to adopt teams for access is a secondary point.  Both repos have a comment about who to contact (a person with admin privs) to get involved, so that's good from the standpoint of communication.

My recommendation is that we should update the documentation in one of our confluence pages that described LSSTDESC GitHub usage, perhaps [this one](https://confluence.slac.stanford.edu/display/LSSTDESC/GitHub+Tips).  Personally I think we should _recommend_ the adoption of teams for admin and write access, but what we should encourage even more strongly is (a) making sure that some person actively working on the repo has admin access, and (b) that person knowing what it means to have admin access, and (c) documenting in the repo README how one can get involved as a developers (how is write access given) and how to get in touch with an admin.  Thoughts?  (This is me putting together Yao's and Heather's suggestions in a particular way, essentially.)

**Comment by johannct** [comment]
`(and similarly, having a team for developers with write access)`: you mean right to push to master? Being able to create a branch should be liberal IMHO

**Comment by johannct** [comment]
I do not remember the general policy of LSSTDESC on github, nor what "write access" covers, but I would prefer liberality in ability to push to branch, and restriction only on push to master.

**Comment by rmandelb** [comment]
For reference - and we should link this on confluence as well - [here's a page](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization) that explains what different permission levels mean.

@johannct - setting restrictions on pushing to master is currently a separate process from establishing who has write access (can push to a new branch in the repo).  And I agree that for most repositories under active development and use, one should have that restriction.

In the LSSTDESC organization we've recommended against giving the entire Members team with hundreds of people write access because giving them write access (can push to a branch) currently also means subscribing them to all repo notifications.  Since GitHub has coupled write access with subscribing to notifications (unnecessarily, in my view!), and since most people don't want to get notifications for basically all DESC repos, we currently recommend giving only read access to the Members team, not write access.  This issue is already outlined on our [reference confluence page for how to use GitHub teams](https://confluence.slac.stanford.edu/display/LSSTDESC/GitHub+Tips).  

However, one can still be liberal with write access by having a clearly defined process to get write access and giving it to all DESC members who request write access, which is what some development teams within DESC are doing.

**Comment by heather999** [comment]
Took a few minutes to review the documentation and examples that we have.  This is an opportunity to improve and clean up!
We can update the [GitHub Tips Confluence documentation](https://confluence.slac.stanford.edu/display/LSSTDESC/GitHub+Tips), though I am a little concerned about people finding that page on their own.  
We also have package templates:
* [LSSTDESC/desc_package_template](https://github.com/LSSTDESC/desc_package_template) 
* [LSSTDESC/pipeline-package-template](https://github.com/LSSTDESC/pipeline-package-template)
* [LSSTDESC/python_package_tempate](https://github.com/LSSTDESC/python_package_template)

two of which are referenced in the [DESC Repo Guidelines](https://confluence.slac.stanford.edu/download/attachments/215859451/Guidelines%20for%20DESC%20Repositories%20v2.pdf?version=1&modificationDate=1563993590000&api=v2) on the PubBoard Confluence page. Those templates haven't been updated in awhile and could be used to incorporate some of the desired documentation as well.  Are we seriously planning to continue supporting and encouraging the use of these templates? If so, we should move forward and refresh them, use them to provide some guidelines, and link them more prominently on Confluence.
