### ISSUE TITLE
[NERSC] permission problems on sn-py3.7

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#36]
**Description**
A clear and concise description of what the issue is.  

I tried to pip install these modules into the community conda environment, 
but don't have permissions. I suspect the first two on the list are already installed. Need these modules for pipeline development.
numpy
pyyaml
coloredlogs
psutil
f90nml

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ X] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by heather999** [comment]
@RickKessler Can you send along the precise error message showing what file(s) lack permission?
I can confirm packages like numpy, pyyaml, coloredlogs are already available.  After doing: `source /global/cfs/cdirs/lsst/groups/SN/software/setup_sn_python.sh` you can do `conda list` to see a full list of what is installed.
For installations, I would generally recommend trying to use `conda install -c conda-forge <packageName>` rather than pip - in the long run that will likely serve you better.  We probably would want to set up a conda environment to try things out and then be able to easily remove broken environments and restart more easily.

Given that we have already gone down the path of installing packages with pip, I tried to do the same logged in as myself rather than as the privileged "desc" user and I see a gcc error when doing :  `pip install psutil`  If using pip rather than `conda install -c conda-forge` I think we have to be more careful about what environment is set up at NERSC to make sure a proper gcc is enabled.

My recommendation is that we set up a conda environment as part of this python installation and define a list of the packages you want to install.  Given a list of packages, we can write a short yaml file and you can execute a simple conda command to set up those packages.  From there, you could continue adding more packages via `conda install -c conda-forge < packageName >`  There will likely still be some packages only available on pypi and that's fine, we would just need to understand their requirements to make sure the environment at NERSC is set up appropriately.
You had mentioned pippin a the previous issues, I am not familiar with Pippin  - is it merely a `pip install pippin`?

**Comment by RickKessler** [comment]
My code doesn't find yaml module even though it is there in conda list ?? To reproduce issue,

1.
source /global/cfs/cdirs/lsst/groups/SN/snana/SNANA_setup.sourceme
   (includes python setup)

which conda
/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/bin/conda
   (doesn't seem to be the community conda?)

2.
conda list | grep yaml
pyyaml                    5.3.1                    pypi_0    pypi
ruamel_yaml               0.15.46          py37h14c3975_0  
yaml                      0.1.7                had09818_2  

3.
submit_batch_jobs.sh -h
Traceback (most recent call last):
  File "/global/cfs/cdirs/lsst/groups/SN/snana/SNANA/util/submit_batch/submit_batch_jobs.py", line 25, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by RickKessler** [comment]
Just realized that my SNANA setup was calling an LSST distribution package that defined python env. After removing this, I get the community python,
which conda
/global/common/software/lsst/common/miniconda/sn-py3.7/bin/conda

And running submit_batch_jobs.sh results in error finding psutil module .. and indeed it's not there in conda list.

**Comment by heather999** [comment]
Ok  - so now that you have the right python installation, let's just make a list of what packages you need and set them up in a new conda environment that uses this python installation.  Then I can hand you the keys and you should be able to continue adding new packages as needed.

**Comment by RickKessler** [comment]
I checked which packages are missing, and there are only 2: 
psutil
f90nml

Do we really need another conda environment ? Would prefer updating the community environment so that anyone else can run these scripts.

**Comment by heather999** [comment]
The idea would be that this conda environment would be the new SN environment that everyone would share.  Effectively, this just means that we will start set up a empty environment from the existing community environment and install conda-forge versions of all the packages you need. They would appear in a `sn-py3.7/envs/sn` subdirectory (assuming we name this `sn`) I'd just update the setup script I put in `/global/cfs/cdirs/lsst/groups/SN/software`, and when anyone runs that, you would be put into that `sn` conda environment.  Everyone would still share this area and you could continue to add more packages, but would try to use `conda install -c conda-forge` rather than `pip install` where possible.

The issue with the existing root community environment is that packages like numpy were set up using pip (pypi) and we would likely want to continue using pip to install additional packages - but that usually runs into problems down the road.  In this case, just doing a `pip install psutil` fails in the community environment due to the need for an appropriate version of gcc. If we create a new conda environment and try to consistently use `conda install -c conda-forge`, we will be more insulated from many of these problems as conda-forge provides their own set of compilers and conda-forge versions of these packages are meant to be more easily installed and upgraded. It would be easier to make this change now rather than later.

**Comment by heather999** [comment]
I think we have this all settled after a direct conversation including Bruno too. We have set up a new sn-py conda environment which is now in use.
