### ISSUE TITLE
[NERSC] Request for w_2020_06 shifter image

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/desc-help#4]
**Description**
Feature request.

@heather999 Could you add a w_2020_06 shifter image at NERSC.  E.g.,

lsstsqre/centos:7-stack-lsst_distrib-w_2020_06

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [X] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by heather999** [comment]
@wmwv I just pulled `lsstsqre/centos:7-stack-lsst_distrib-w_2020_06` into shifter. Just let me know if you have any trouble with it or hopefully that this works as expected.

**Comment by wmwv** [comment]
Thank you!  It works.

**Comment by wmwv** [comment]
@heather999 I just tried using this image again today and I couldn't get it to work:

```
[cori08 tmp] shifter --image lsstsqre/centos:7-stack-lsst_distrib-w_2020_06
sh-4.2$ source /opt/lsst/software/stack/loadLSST.bash
Could not find conda environment: lsst-scipipe-1a1d771
You can list all discoverable environments with `conda info --envs`.

/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/v20.0.0/stack/miniconda3-py37_4.8.2-1a1d771 in $EUPS_PATH does not contain a ups_db directory, and is being ignored
Unable to unsetup eups LOCAL:/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/v20.0.0/eups/2.1.5: Table file not found for eups LOCAL:/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/v20.0.0/eups/2.1.5 ((none)): /cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/v20.0.0/eups/2.1.5/ups/eups.table
```

**Comment by wmwv** [comment]
The `/cvmfs` directory is not mounted under the shifter image.

**Comment by wmwv** [comment]
Maybe this doesn't matter anymore.  The idea originally was to get a compatible compiler, and gcc 7.5 (which is a new NERSC default) seems to work fine.

**Comment by heather999** [comment]
I guess I'm not understanding what you want to do here.  You could either use the CVMFS installations or shifter images.  w_2020_06 is rather old.  Do you need that version of the stack specifically?  That is probably still using the system (NERSC) compilers, but more recent stacks (since Spring 2020) are going to use the conda compilers which will make your life much easier.

I just refreshed the lsstsqre/centos:7-stack-lsst_distrib-w_2020_06 shifter image at NERSC - I don't know that they purge images, but that is from last year, and likely hasn't been accessed recently.

I also just pulled lsstsqre/centos:7-stack-lsst_distrib-w_2021_03, which is a current version of the stack using those conda compilers.  You might try that.

If you would like to use CVMFS, there are some setup scripts that would let you do that:
`source /global/common/software/lsst/cori-haswell-gcc/stack/setup_any_stack.sh w_2021_03`

after that - you can try compiling things using an appropriate compiler.. if w_2020_06, that's probably gcc 8.3.0 and if it's a recent stack - you're going to be using the conda supplied compilers, which shields you from NERSC defaults.

**Comment by wmwv** [comment]
> You could either use the CVMFS installations or shifter images.

Right, I wanted to use the `shifter` image.  The problem was that the shifter image I was getting was somehow using an `/opt/lsst/software/stack/loadLSST.bash` that referred to `/cvmfs`.  I don't really understand how that could have happened.

The newly refreshed image works fine.
