### ISSUE TITLE
[NERSC] Fast-PT in the desc environment 

### ISSUE THREAD

**Issue by empEvil** [LSSTDESC/desc-help#54]
**Description**
I was wanting to test some calculations done with CCL's Fast-pt component in a jupyter notebook on nersc, but apparently fast-pt is not part of the DESC environment. Can it be added? 

Choose all applicable topics by placing an 'X' between the [ ]:
- [x] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

I believe the module can be found at https://github.com/JoeMcEwen/FAST-PT . But you could probably also ask @jablazek.

**Comment by johannct** [comment]
If fastpt is a new dependency of CCL, CCL install itself needs to be updated. Is CCL team requesting that fast-pt be added as a dependency? @elisachisari @damonge ? In the meantime you can use %pip to install it locally while you test CCL fast-pt functionalities.

**Comment by johannct** [comment]
fast-pt seems to depend on numpy, scipy, and matplotlib, so clearly that should not be a problem to add it. But CO would like to organize such requests for additions so that the DESC ecosystem does not get out of control. So I would appreciate some context as well, as to why it needs to be added to the ecosystem, rather than be an option that individuals can always exercise with a local install on top of the DESC ecosystem.

**Comment by heather999** [comment]
That all said, I would much prefer that dependencies that are commonly needed, be part of the environment rather than actively encouraging every individual to add packages in their own areas. We know this leads to problems down the road, but we don't want to pull in every possible package out there.
We need to encourage more communication with the WGs about what packages are needed and how to put in requests.  CO needs to write up some guidelines (preferably conda-forge installable, release tags, actively maintained packages..) and as previously discussed, provide a CI environment that allows users to trigger testing of new packages.  For now, desc-python-bleed is helpful to at least evaluate that a requested package works without conflicts.  And in those cases where a package meets some minimal criteria and is of general interest to DESC - it should be considered.

Concerning this specific request for fastpt, it is not a dependency of CCL, but could be considered a recommended useful package: https://ccl.readthedocs.io/en/latest/source/installation.html#getting-fast-pt
Input from the CCL group is very welcome.

**Comment by johannct** [comment]
Installing in user's own area here is just to let Eske get going while this is resolved. Of course this is not the way to go for a commonly used package within DESC. I reiterate the main point IMHO : if fast-pt is recommended by CCL, then CCL should be calling for its addition, not a user of CCL.

**Comment by c-d-leonard** [comment]
As @heather999 mentioned: fast-pt is not a strict dependency of CCL but it is an optional package enables some functionality (non-linear power spectra and intrinsic alignments using perturbation theory methods). I think it is reasonable to consider it as something that will be widely used by CCL users consider its use e.g. in DES currently for intrinsic alignment and galaxy bias modelling.

I have to admit I may have dropped the ball here on communication wrt the DESC NERSC environment. Could someone point me (as CCL lead) to some guidance as to when I should open a dialogue with respect to this kind of thing, and with who?

**Comment by johannct** [comment]
@c-d-leonard Exactly as @empEvil did : by opening an issue here, possibly also opening a thread for discussion on #desc-nersc.  I understood that it was not a strict dependency to build CCL. The question I am asking and that you have answered above is : does CCL@DESC consider that this option is needed for DESC in production? CO cannot answer this question on its own, and cannot be expected to add such dependency on the basis of a single user's request. If I may suggest a more straightforward route next time: Eske could have mentioned to CCL community that current desc production system was not including the optional fast-pt; discussion would then occur there as to whether DESC needs it, and then once a decision is made, CCL leaders would make a request to CO via a new github issue. Sorry if I sound nitpicking, but if we do not follow some guidelines and respond favorably to all possible requests from DESC members, the system will quickly become bloated and unmanageable; a case in point would be that CCL needs some version of fast-pt, but not any version..... CO would quickly go down a spiral of pain. Related to this last point : CO of course will install the latest tag, not a master, not a previous tag. But ideally all this should be defined by the knowledgeable people when they request inclusion.

**Comment by jablazek** [comment]
Hello all. I meant to respond earlier - apologies for the delay. I agree with @c-d-leonard's assessment that, while optional, fast-pt will be in wide enough use to warrant being part of the environment.

fast-pt installation is possible through conda (it looks like we need to update the CCL documentation on this point). @johannct, that is the preferred route, I assume, and should simplify versioning as long as we (CCL and FAST-PT dev teams) keep that up to date.

**Comment by johannct** [comment]
Thanks a lot for clearing it up. conda is certainly fine.

**Comment by heather999** [comment]
Sorry for the late reply. I think it is also on CO to document what we expect so conveners of other WGs know what we hope to happen. Now on the ever-increasing to do list.  In the meantime, I am adding fast-pt to desc-python:bleed first and then to desc-python.

**Comment by heather999** [comment]
FWIW, fast-pt is now included in desc-python, desc--python:bleed, and soon will be included in desc-stack-weekly and desc-stack-weekly-latest
