### ISSUE TITLE
[NERSC] Add DESC product

### ISSUE THREAD

**Issue by Catarina-Alves** [LSSTDESC/desc-help#66]
**Description**
I would like to add the DESC product [snmachine](https://github.com/LSSTDESC/snmachine) to NERSC so anyone could use it in their analysis. What should I do it include it there?

Choose all applicable topics by placing an 'X' between the [ ]:
- [x] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [x] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by heather999** [comment]
Hi @Catarina-Alves Thank you for reaching out about snmachine. This looks like a request to add `snmachine` to `desc-python`, which is installed at NERSC (and IN2P3).  `desc-python` is available to use both in jupyter and via command-line or batch jobs.  I'm out on vacation today - but will look at this on Monday.  We are trying to transition to a more formal process to include packages in `desc-python`, with a very light set of requirements such as tagged releases, clear installation instructions, and some demonstration that our automated build of desc-python is compatible with both new and updated packages.
It looks like `snmachine` is tagged 2.0.0 and is available for installation via conda.  I need to set up a build of desc-python which includes snmachine and we can discuss this further next week!

**Comment by Catarina-Alves** [comment]
Thank you, I look forward to it.
`snmachine` is also instalable through pip, if that is easier to install.

**Comment by Catarina-Alves** [comment]
Hi @heather999, I just wanted to follow up on this.
Do you have a timeline as to when this might be ready? I do not need this before September but it would be great to have `snmachine` in NERS in September.

**Comment by heather999** [comment]
Hi @Catarina-Alves I'm really hoping to have snmachine in desc-python this week and certainly before September.  Once I have it included - can you recommend an easy way to test it? I suspect it'll be fine, but having some way to confirm that it's working properly would be helpful.  I'll let you know as soon as it is available!

**Comment by Catarina-Alves** [comment]
Thank you.
`snmachine` has some example notebooks (see [here](https://github.com/LSSTDESC/snmachine/tree/dev/examples)). If these are running without problems, `snmachine` should be working properly.

**Comment by heather999** [comment]
HI @Catarina-Alves I made an initial test of installing `snmachine` and took a look at the instructions here: https://lsstdesc.org/snmachine/install.html#using-conda
It looks like the snmachine dependencies need to be installed manually, and that doing `pip install snmachine` doesn't pull in all the packages needed, like `lightgbm`? Typically, the pip install will also install required dependencies and could even have optional dependencies that are installed for a "full" installation versus a minimal one. 
I'm guessing all the dependencies are in: https://github.com/LSSTDESC/snmachine/blob/main/environment.yml.
To include snmachine in desc-python, it needs to be able to fully install itself and its required dependencies, otherwise we'd be left trying to manage snmachine's dependencies in desc-python itself, rather than have snmachine dictate what it needs.
I think this is a relatively easy fix though, the setup.py or setup.cfg could include an `install_requires` directive that lists what `snmachine` depends on.  `sncosmo` has an example: https://github.com/sncosmo/sncosmo/blob/master/setup.cfg

**Comment by Catarina-Alves** [comment]
Hi @heather999, thank you, I tried to fix the issue.
Is the new setup in [here](https://github.com/LSSTDESC/snmachine/blob/fix-install/setup.py) good, or do I need to do something different?

**Comment by heather999** [comment]
Hi @Catarina-Alves Thank you - that's a start, I'm not sure this is a list of what `snmachine` minimally needs to run correctly.  I'm wondering if something like `jupyter` is really required or just useful to have if you're running a notebook.  Ultimately, we will also need this updated snmachine to be tagged and uploaded to pypi -that way when I go to do `pip install snmachine`, all the dependencies will be recognized and installed as well.

**Comment by Catarina-Alves** [comment]
Thank you @heather999. 
I have a question regarding the first part of your answer. Should I only include in `install_requires` the base packages the `snmachine` uses? If so, do I leave the other packages in `environment.yml` like they currently are?
And how basic do I need to go? `jupyter` is only useful if you want to run a notebook, but we have notebook tutorials in `snmachine`. Similarly with the plotting packages (e.g. `matplotlib`, `seaborn`) are only used for making plots. 
On a different note, I can remove the `python>=3.7` `install_requires`, and add it to `python_requires=">=3.7"`.

Regarding the second part of your answer. I will tag and upload to pypi after solving this issue.

**Comment by heather999** [comment]
Hi @Catarina-Alves 
the `setup.py` and `environment.yml` are serving two different purposes.  The setup.py is really just for installing your package and the minimal dependencies `snmachine` needs to run.  The `environment.yml` is a file that lists all the packages your group is recommending a user might want to install - so it includes "extra" things like jupyter so people can run your notebooks. 
Up to now, it looks like in the `snmachine` documentation, users need to install all the dependencies plus useful packages on their own using `environment.yml` and then install `snmachine`.  
Instead of doing that, the more typical thing to do would be to update `setup.py` and update the `snmachine` on PyPI to allow users to install `snmachine` completely, including the required dependencies - just enough that they can use `snmachine`.  The `environment.yml` could be updated to add additional useful packages - but has no direct implications for the `snmachine` install for a user doing: `pip install snmachine`.  Doing that pip install should be enough for someone to use your package in most cases.

I'm going to make some suggestions on your open `snmachine` github issue to help define a set of packages that you absolutely need.

**Comment by heather999** [comment]
Hi @Catarina-Alves 
I see the update was merged to snmachine - so next would be to update PyPI so we can install this version in the DESC python environments.  I'd like to open a PR on snmachine to suggest this could be an automated procedure, so that future releases of snmachine are pushed to PyPi and made available.  I"ll do that now and perhaps we can work through the steps to store the PyPI token needed to allow this to work?

**Comment by Catarina-Alves** [comment]
Hi @heather999 I just wanted to know if you found any issues, or if snmachine was able to be integrated into desc-python (thus closing this issue and issue https://github.com/LSSTDESC/snmachine/issues/255).

**Comment by heather999** [comment]
hi @Catarina-Alves Sorry for the delay!  I haven't found any issues. I'm working to get a new version of desc-python out, first as `desc-python-dev` which will include `snmachine` and then by the end of the week, I'm hoping to release a new `desc-python` with `snmachine`.  I'll keep you updated on progress!!

**Comment by Catarina-Alves** [comment]
Thank you. I am glad that there were no issues

**Comment by johannct** [comment]
furthermore conda/pip installation typically install stuff away from the user work directory (under a virtual env directory in .local or under the conda distrib etc...) so quickly it becomes impractical to leave them there. Likewise for tests actually, though I understand the point of having them around..... one can actually pytest on them, but one has to find them and likely chdir first (running tests can also suppose a certain way to preload the packages/module that may be different than the install final system if I am not mistaken).

**Comment by Catarina-Alves** [comment]
`snmachine` has now utils as a subpackage. This change was also propagated to pip install (v2.0.0.post3). Is there anything else to do, or can we close this issue @heather999?

**Comment by heather999** [comment]
Hi @Catarina-Alves Great!
I think the final point is that after conferring with the Johann and Gautham (now a few months ago!) - we'd like `snmachine` to be part of the `sn-py` environment rather than `desc-python`.  It seems to be a better fit.
I have a new sn-py environment set up at NERSC which also includes the LSST Sci Pipelines and all the packages that I'm aware of that are of interest to the SN group.  Some [ongoing discussion on this issue.](https://github.com/LSSTDESC/desc-help/issues/77)
Does that sound ok to you?

**Comment by Catarina-Alves** [comment]
Hi @heather999, yes, it seems great. Thank you

**Comment by heather999** [comment]
HI @Catarina-Alves 
Finally back to this - there is a new `td_env` now available at NERSC which includes `snmachine`.
For now this environment is still a test, so to use it at the Cori command line you would do:
`source /global/cfs/cdirs/lsst/groups/TD/setup_td_dev.sh`
Then you're in the environment and will have access to the LSST Sci Pipelines, plus snmachine and a few other packages of interest to SN and SL.

There is also a new jupyter kernel for this environment available named `desc-td-env`. 
To enable it, you would redo the DESC kernel setup you likely have already done in the past:
`source /global/common/software/lsst/common/miniconda/kernels/setup.sh`
That will re-install all the available kernels (like desc-python, desc-stack, etc) and add this new desc-td-env
https://confluence.slac.stanford.edu/display/LSSTDESC/Using+Jupyter+at+NERSC#UsingJupyteratNERSC-setup

The next time you start up a fresh jupyter.nersc.gov, the desc-td-env should be one of the available kernels.

We're hoping to make this new td_env the "stable" TD environment in the next two weeks - so please give it a try and let me know if you have trouble or success!

**Comment by Catarina-Alves** [comment]
Hi @heather999, 

I find a problem when I import the modules `sndata` and `snfeatures` from `snmachine`; they require `sncosmo`, which is not part of the `desc-td-env`. `sncosmo` is part of the requirements of `snmachine`; you can see it in `environment.yml`. I had no problems with the other `snmachine` modules so far.

**Comment by heather999** [comment]
Thank you @Catarina-Alves 
I fixed the problem - and will get a new install of the environment set up for you to test!  I'm stuck with a hopefully transient issue re-installing the underlying LSST Sci Pipelines environment, but hopefully that will be sorted out by the morning.

**Comment by heather999** [comment]
Hi @Catarina-Alves 
There were a few DNS problems at NERSC that delayed this.. but there is now a new build of the td_env that includes 'sncosmo` as well as `snmachine`.
You can use this updated environment at NERSC by doing: `source /global/cfs/cdirs/lsst/groups/TD/setup_td_dev.sh`
Please give it another try and let me know how it goes!

**Comment by Catarina-Alves** [comment]
I updated the environment but I now find a strange problem. When I run `from snmachine import snfeatures`, the kernel dies. I am not sure why because the other modules are loaded without any issue. Can you also reproduce this strange behaviour?

**Comment by heather999** [comment]
Hi @Catarina-Alves I do see the same error and I traced it back to this `import pymultinest` here: https://github.com/LSSTDESC/snmachine/blob/abe55bac3154311477f108861274b3e453bc2285/snmachine/snfeatures.py#L31
This conda environment has mpi4py installed and built against the NERSC cray mpich libraries - which really only works on the batch nodes, not the login nodes or in jupyter where we typically run on login nodes as well.  This was discussed in an old issue on the pymultinest github repo: https://github.com/JohannesBuchner/PyMultiNest/issues/113

pymultinest has an optional dependency on mpi4py, it doesn't absolutely need it to run, and the [code is written to check if importing mpi4py works, and if it doesn't, then the mpi4py features are just not available](https://github.com/JohannesBuchner/PyMultiNest/blob/e2f2e75bdb53d2f8dbd48874744cf4dd50e986e1/pymultinest/run.py#L55).  In this case at NERSC, the attempt to import mpi4py results in a fatal error which the exception handling in pymultinest doesn't catch. I have some ideas about how to deal with this.. hope to know more in the morning.

**Comment by Catarina-Alves** [comment]
I do not use `pymultinest` often on `snmachine` but it is an option available to users.

**Comment by heather999** [comment]
I've opened an issue on pymultinest: https://github.com/JohannesBuchner/PyMultiNest/issues/209 with one potential way to work around this.
In the meantime, I'll see if I can modify the set up so that this doesn't cause a fatal error and pymultinest will just continue without mpi on the NERSC login nodes.

**Comment by heather999** [comment]
@Catarina-Alves I have a work-around in place that prevents MPI from being used if we run python from a login node or jupyter session, but allows MPI if we're on a batch/compute node. I'm now able to successfully execute: `from snmachine import snfeatures`.  Please give it another try when you get a chance and let me know how it goes!

**Comment by Catarina-Alves** [comment]
Seems all right now, thanks
