### ISSUE TITLE
[NERSC] Planning CSCRATCH use for ELASTICC and brokers

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#72]
**Description**
A clear and concise description of what the issue is.  

For preparing simulated alerts for ELASTICC and brokers, we may need to write 100 million files to scratch before tarring up groups. However, we would first like to check if there are any obvious problems with writing so many files to scratch.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ x] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by TomGlanzman** [comment]
100 million files (in the same directory?) is quite a large number.  As @heather999 Heather points out, there is the inode limit.  Depending on how the files are read and written, you could see some serious degradation (at best) and complete hangs (at worst).  I've had some very bad experience when the _rate_ of file opens/closes/creates/deletes gets too high.  The performance behavior can be very non-linear; you may need to perform some experiments to see where problems begin to occur.

Some of the consultants at NERSC may have experience in this usage domain.  It might be useful to probe them with a query to their support team.

**Comment by johannct** [comment]
@TomGlanzman Thanks Tom, yes the inode danger zone was on my radar and I mentioned it to the team. We need to do some checks or preemptive work.

**Comment by heather999** [comment]
If I'm following, 1 directory per night for 3 years, ~1000 directories, so that 100 million files is spread across 3 years?  Meaning that per night you might receive ~100k files?  
The files are aggregated nightly, so one tarball per night?
I can't necessarily imagine leaving these files on CSCRATCH for 3 years - they would have to be backed up elsewhere at least.  Is there a need to keep them all on CSCRATCH due to some performance concerns such as for follow-on processing (classification and ultimately DM processing?) at NERSC? Is it possible to migrate the tarballs off CSCRATCH after some period of time - even if they need to be copied back to CSCRATCH for later processing?
Started to poke around to look from some notes to try to find some details.  Found the Sept 10th [ELAsTiCC Alert generation slides](https://docs.google.com/presentation/d/1AplxXwTfviyMXOrfuBh17WWA6bue-TOD7G7Kem3Kn_I/edit#slide=id.gef0687339c_1_0) and 
https://github.com/LSSTDESC/plasticc_alerts
