### ISSUE TITLE
[NERSC] update emcee available via desc-python

### ISSUE THREAD

**Issue by humnaawan** [LSSTDESC/desc-help#8]
**Description**
I'd like to request that the `emcee` package that comes with the current `desc-python`  be updated from its current version of 2.2.1 to the latest release 3.0.2.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] Cori interactive command line
- [ ] Batch jobs
- [x] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by heather999** [comment]
Hi @humnaawan `desc-stack` already has emcee 3.0.2 installed in it.  I just updated `desc-python` to use emcee 3.0.2.  Just let me know if there are any problems!

**Comment by humnaawan** [comment]
awesome, thank you @heather999! so i'm able to use the `progress=True` in jupyerlab when running the `emcee` chains but it says `WARNING:root:You must install the tqdm library to use progress indicators with emcee`. i have the progress bar via command line though.

**Comment by heather999** [comment]
Hmm.. can you give me a code snipped so I can reproduce the problem in my own notebook?

**Comment by humnaawan** [comment]
okay so you can run a dummy `emcee` chain in `desc-python`:

```
import emcee as mc
import numpy as np

def dummy_func(p):
    return p

npar = 4
p0 = np.zeros(npar) + 1
# setup sampler
nwalkers = 10
nsteps_burn = 20
nsteps_per_chain = 50
sampler = mc.EnsembleSampler(nwalkers, npar, dummy_func)

#Fsirst sample for each walker
par0 = (p0)[None,:] * (1 + 0.001 * np.random.randn(nwalkers, npar))

out = sampler.run_mcmc(par0, nsteps_burn, progress=True)
sampler.reset()
```
and you'll see
```
WARNING:root:You must install the tqdm library to use progress indicators with emcee
```

If I run this is in `desc-python-dev`, I get the progress bar without errors, which is great.

**Comment by heather999** [comment]
That's very good news and I can reproduce the same results - it fails in `desc-python` and now works in `desc-python-dev`! 
I think what is happening is NERSC maintains the JupyterLab extensions in jupyter.nersc.gov and at some point they install a version of those extensions that is incompatible with older versions of packages that rely on those extensions, like emcee.  I'm in touch with NERSC to see if I can keep track of their extension versions so I be aware of incompatibilities and hopefully keep up with necessary updates before everyone else has to experience failures.
I'll finish getting `desc-python-dev` set as `desc-python` - so that this will work for everyone using the production version of the jupyter kernel.

**Comment by humnaawan** [comment]
awesome, thank you!

**Comment by heather999** [comment]
`desc-python` has been updated to the new version, so emcee should work as hoped.  Just let me know if you run into problems.

**Comment by heather999** [comment]
I'm going to close this and address the other open issues.  If there are any remaining problems, please re-open this issue or open a new one.
