### ISSUE TITLE
td-env 

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/desc-help#82]
**Description**
A clear and concise description of what the issue is.  

version mismatch between CFITSIO and linked library.

Choose all applicable topics by placing an 'X' between the [ ]:
- [X] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**
1. 
When running `desc-td-env` Jupyter environment, as set up with

source /global/cfs/cdirs/lsst/groups/TD/setup_td_dev.sh
and then
source /global/common/software/lsst/common/miniconda/kernels/setup.sh
2. Start new Jupyter kernel with `desc-td-env`3. 
3. Run `from lsst.daf.butler import Butler`
5. See error:

"""

WARNING: version mismatch between CFITSIO header (v4.000999999999999) and linked library (v4.01).

WARNING: version mismatch between CFITSIO header (v4.000999999999999) and linked library (v4.01).

WARNING: version mismatch between CFITSIO header (v4.000999999999999) and linked library (v4.01).

```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by wmwv** [comment]
I don't get this error with the current `desc-stack-weekly`

**Comment by heather999** [comment]
@wmwv This is a warning due to how cfitsio checks its version - apparently a rounding error.  So an upstream, non-fatal issue.  Noted by the DM folks on Slack, and in the [healpy repo](https://github.com/healpy/healpy/issues/754).  
I don't see that there is a definitive fix available - perhaps when healpy patches the cfitsio version checking and rubin-env updates to that version of healpy, this warning will disappear - though reading the Slack thread, it wasn't clear which package(s) were causing those warning messages.  In the meantime, I think it's safe to ignore.

You won't see this in desc-stack-weekly, since that's an older version of the stack (and something I hope to upgrade this week) and older versions of the dependencies.

**Comment by wmwv** [comment]
Thanks, @heather999   The idea that a rounding error is involved is mildly terrifying.  Versions are not floats and I'm deeply worried about anything that treats them that way.  I appreciate that you're on top of it and track the issue.

**Comment by wmwv** [comment]
@rknop I see what you're saying now that `4.000999999...` = `4.001` which is still different than `4.01`

**Comment by heather999** [comment]
Closing - we understand the issue, I believe we are still waiting for a fix upstream from us.
