### ISSUE TITLE
need to install ROOT

### ISSUE THREAD

**Issue by RickKessler** [LSSTDESC/desc-help#89]
**Description**
A clear and concise description of what the issue is.  

Need CERN ROOT installed as part of DESC TD environment. While ROOT is not needed for SNANA  simulations, it is useful for analysis such as light curve fitting. A DESC member is starting an analysis that needs ROOT functionality.

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems
- [x] TD environment
- [ ] 
**To Reproduce**

**Screenshots**

**Comment by cwwalter** [comment]
Note ROOT is now available in conda-forge:

https://anaconda.org/conda-forge/root

**Comment by RickKessler** [comment]
Forgot to mention that initial use of ROOT is compiling with C codes.

**Comment by heather999** [comment]
@RickKessler any particular version of ROOT? I would be inclined to use the conda-forge install and pick up the latest release which appears to be v6.26.6

I can add this to td_env dev installation today and we can see if that satisfies your needs.

**Comment by RickKessler** [comment]
v6.26.6 should work, and indeed let's start with dev.

**Comment by heather999** [comment]
Unfortunately installing root using conda-forge fails due to a need for at least python3.9.
td_env is stuck on python 3.8 since we are using LSST Sci Pipelines w_2022_22. Until we upgrade the version of LSST Sci Pipelines, we can't move python version easily.
So for right now, I cannot install ROOT with conda-forge.  We could attempt to use the ROOT module available at NERSC.  My recommendation would not be the default when running the `setup_td_prod.sh` script, rather we'd have a flag for those that plan to run ROOT analysis and the ROOT module would be loaded in only that case.  I've briefly tried this out and ROOT functions, I would just hesitate to set up ROOT this way for those that really don't need it.

Does that sound ok for now @RickKessler ?

**Comment by heather999** [comment]
After more Slack discussion, moved to use root_base from conda-forge which does seem compatible with w_2022_10.
root_base is now included in td_env and will be released as "stable" Monday, Sep 19, 2022
https://github.com/LSSTDESC/td_env/issues/68
