### ISSUE TITLE
Including $FIRECROWN_EXAMPLES_DIR in Perlmutter TD setup script

### ISSUE THREAD

**Issue by am610** [LSSTDESC/desc-help#96]
In `/global/cfs/cdirs/lsst/groups/TD/setup_td_dev.sh`,
I would urge you to please define 
`$FIRECROWN_EXAMPLES_DIR` 

Currently `$FIRECROWN_DIR` is only defined, as
`/global/common/software/lsst/cori-haswell-gcc/stack/td_env-dev/81491/firecrown`

Similarly `$FIRECROWN_EXAMPLES_DIR` would be 
`/global/common/software/lsst/cori-haswell-gcc/stack/td_env-dev/81491/firecrown/examples`

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [ ] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**

**Screenshots**

**Comment by heather999** [comment]
HI @am610 Thanks for reaching out!  I have actually been wondering about how to handle `$FIRECROWN_EXAMPLES_DIR`. I was originally thinking people might want to set it themselves to point to their own local copy for firecrown and the examples.  The issue is making sure folks download a compatible (or the same) version of firecrown so they don't experience any trouble if the API in firecrown changes that affect the examples.  
We could set `$FIRECROWN_EXAMPLES_DIR` and point it to the copy included with the td_env installation. People can still choose to reset `FIRECROWN_EXAMPLES_DIR` and point to their own area.  Does that sound ok?

**Comment by heather999** [comment]
Hi @am610 td_env dev has been updated to define `$FIRECROWN_EXAMPLES_DIR`.  You can try ths out by doing:
`source /global/cfs/cdirs/lsst/groups/TD/setup_td_dev.sh`

Just let me know if you see any problems.
