### ISSUE TITLE
[NERSC] New packages in conda environment lsst-scipipe-w_2022_10

### ISSUE THREAD

**Issue by anaismoller** [LSSTDESC/desc-help#97]
**Description**
To run machine learning classifier framework SuperNNova for time-domain analysis, we need to add some libraries to the lsst-scipipe-w_2022_10 Honda environment. I would appreciate installing them.

SuperNNova is currently used for Supernova analysis at DES and will be used in LSST-TD group 
https://github.com/supernnova/SuperNNova 

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [ ] jupyter terminal
- [ ] Cori interactive command line
- [X ] Batch jobs
- [X ] python
- [ ] CSCRATCH
- [ ] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**To Reproduce**
1. Go to `/global/cfs/cdirs/lsst/groups/TD/SOFTWARE/classifiers/SuperNNova`
2. `./run_tests.sh`
3. ModuleNotFoundError: No module named 'torch'4. 
this will continue for all packages not installed

Two options for the installation (probably contains some already existing packages):
`conda install --file /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/classifiers/SuperNNova/env/conda_env_gpu_linux64_2023.txt`

or in the env (I think this is all that is missing)
`conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia`
```
pip install h5py==3.8.0 \
     matplotlib \
     colorama \
     tqdm \
     scipy \
     natsort \
     pandas \
     astropy \
     ipdb \
     scikit-learn \
     pytest \
     unidecode
```

Thanks!

**Comment by heather999** [comment]
Hi @anaismoller !  Thank you for the request.  Now for some questions!
It looks like you want to support GPUs at NERSC.  I think that will work out - it will just take a little care.
Are you looking for just the dependencies of SuperNNova to be included in td_env or SuperNNova itself to be installed directly in td_env?  Re-reading, it sounds like you just want to include the dependencies for now.

**Comment by anaismoller** [comment]
Hi @heather999 thanks for the swift reply! For the time being we only need the dependencies. I was discussing with @RickKessler and eventually having the SN tools as part of the available packages would be great.

For the GPU support, is it very tricky? It really is key for the training of the ML algorithms (else it takes very long in CPU). From the SuperNNova side we need that the environment includes the GPU pytorch library which is in the file I sent.

**Comment by heather999** [comment]
Hi @anaismoller Haven't forgotten you - I had an issue to work out with mpich after the recent Perlmutter upgrades.  Ayan is helping me to confirm that things are working as expected.  Once that is done - I can start adding these new updates to the integration version of td_env and we can test those out!

**Comment by anaismoller** [comment]
Thanks @heather999 ping me if there is somehow I can help!

**Comment by heather999** [comment]
HI @anaismoller Sorry for the delay..  I am becoming uncertain whether I can enable GPU support in the same environment where we have the LSST Science Pipelines installed - at least at NERSC.  If I could use openmpi things would be a bit easier, but right now that isn't an option on Perlmutter.  I have a couple more ideas to try, including setting this up in a container - but in the meantime I have some more questions!
  
For this work - is there a need for the LSST Science Pipelines or would an environment that enables GPUs but without the LSST Sci Pipelines be ok?  
If you do need the LSST Sci Pipelines, I also wanted to confirm - for your work, do you need the w_2022_10 version?  The td_env has since moved to use a more recent LSST Sci Pipelines (w_2022_32) - which might make this easier to set up.

**Comment by heather999** [comment]
HI @anaismoller I apologize for the delay, I was out last week.
There is now a test environment available, but I do have one question concerning the version of pandas.  In your env, I see pandas 1.5.3 while I would typically pick up the more recent release 2.0.2.  When using pandas 2.0.2, running run_tests.sh results in pandas errors like:
```
 File "/global/cfs/cdirs/desc-td/SOFTWARE/classifiers/SuperNNova/supernnova/utils/data_utils.py", line 649, in save_to_HDF5
    tmp = pd.Series(settings.list_filters_combination).append(df["FLT"])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/lsst/gitlab/td_env-int/2023-06-07-35-29/conda/envs/td-gpu/lib/python3.11/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Series' object has no attribute 'append'. Did you mean: '_append'?
ok
```

I believe this can be fixed by migrating to the newer syntax to use concat rather than append, see the [pandas documentation](https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html#deprecations).

For now, I've reverted to pandas 1.5.3, but it would be preferred to keep up to date with the latest versions of the various packages unless there is some absolute need to stay pinned to an earlier version.

Anyway - to try this out yourself, you can set up the environment by doing the following:

`source /global/cfs/cdirs/lsst/groups/TD/setup_td_int.sh -g`

That `-g` is used to indicate you want the GPU environment.

Just let me know if there are any packages missing - this is a very bare bones environment so far but it seems to be enough to run this particular test.  Once things looks good, we can move this to a "dev" version of td_env and ultimately make it the new production version.

**Comment by heather999** [comment]
I'm also noticing an hdf5 error, which I think is an issue not with the environment but with the code in line 249 of file `/supernnova/utils/training_utils.py`:

`settings.data_types_training = hf["data_types_training"][:].astype(str)`

wondering if this is related: https://github.com/h5py/h5py/issues/1779

```
[Features used] FLUXCAL_g FLUXCAL_i FLUXCAL_r FLUXCAL_z FLUXCALERR_g FLUXCALERR_i FLUXCALERR_r FLUXCALERR_z delta_time g gi gir girz giz gr grz gz i ir irz iz r rz z
Traceback (most recent call last):
  File "/global/cfs/cdirs/desc-td/SOFTWARE/classifiers/SuperNNova/run.py", line 199, in <module>
    raise e
  File "/global/cfs/cdirs/desc-td/SOFTWARE/classifiers/SuperNNova/run.py", line 53, in <module>
    train_rnn.train(settings)
  File "/global/cfs/cdirs/desc-td/SOFTWARE/classifiers/SuperNNova/supernnova/training/train_rnn.py", line 255, in train
    list_data_train, list_data_val = tu.load_HDF5(settings, test=False)
  File "/global/cfs/cdirs/desc-td/SOFTWARE/classifiers/SuperNNova/supernnova/utils/training_utils.py", line 249, in load_HDF5
    settings.data_types_training = hf["data_types_training"][:].astype(str)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/global/common/software/lsst/gitlab/td_env-int/2023-06-20-37-31/conda/envs/td-gpu/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 827, in __getitem__
    selection = sel2.select_read(fspace, args)
  File "/global/common/software/lsst/gitlab/td_env-int/2023-06-20-37-31/conda/envs/td-gpu/lib/python3.10/site-packages/h5py/_hl/selections2.py", line 101, in select_read
    return ScalarReadSelection(fspace, args)
  File "/global/common/software/lsst/gitlab/td_env-int/2023-06-20-37-31/conda/envs/td-gpu/lib/python3.10/site-packages/h5py/_hl/selections2.py", line 86, in __init__
    raise ValueError("Illegal slicing argument for scalar dataspace")
ValueError: Illegal slicing argument for scalar dataspace
```

**Comment by anaismoller** [comment]
Hi @heather999 

thanks for all of this! I usually freeze versions to ensure reproducibility. Some upgrades don't make a difference but in this case with pandas, it does and affects other functionalities ! 

We are right now working on upgrading SuperNNova to be compatible with newer packages. This would fix all this issues (and some others) together with new tests that are more comprehensive.

 Would it be ok to pause this issue until we have the full changes and tests? Timeline wise, end of August is the goal. 

Thanks,

Anais

**Comment by heather999** [comment]
HI Anais - yes that is totally fine. I just didn't want to hold you up. Just let me know when we should come back to this!

**Comment by anaismoller** [comment]
Thanks Heather! I rather have a new release to be sure all the setup lasts for long ;)

I'll come back to you on this when it is ready

Cheers,

Anais
